# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "TermishTheme"
license = "MIT"
licenselink = "https://github.com/yilkalargaw/termishTheme/blob/master/LICENSE"
description = "A minimal responsivetheme designed to look like a texteditor and to work well whithout javascript"
homepage = "https://github.com/yilkalargaw/termishTheme"
tags = ["minimal", "dark-mode", "clean", "simple", "blog", "editor"]
features = ["responsive"]
min_version = "0.41.0"

[author]
  name = "Yilkal Argaw"
  homepage = "https://github.com/yilkalargaw/"
